[PHP]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Geral
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

date.timezone = America/Sao_Paulo
memory_limit = 512M
max_execution_time = 300
max_input_time = 300

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Uploads
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

upload_max_filesize = 100M
post_max_size = 100M
max_file_uploads = 20

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Erros
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

display_errors = On
display_startup_errors = On
log_errors = On
error_reporting = E_ALL

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; OPcache
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

opcache.enable=1
opcache.enable_cli=1
opcache.validate_timestamps=1
opcache.revalidate_freq=0
